name: Snake Animation
on: [push, schedule: [{cron: '0 0 * * *'}], workflow_dispatch]
jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Platane/snk@v3
      with:
        github_user_name: 'shubhamshrivastava11'
        outputs: |
          dist/o/github-contribution-grid-snake.svg
    - name: Push snake
      uses: mikeal/rpublish@v2
      with:
        path: ./dist/o
        branch: gh-pages
